-- Drop tables if they exist (order matters due to foreign keys)
DROP TABLE RESERVATION_SLOT_DETAILS CASCADE CONSTRAINTS;
DROP TABLE VEHICLE CASCADE CONSTRAINTS;
DROP TABLE OWNER CASCADE CONSTRAINTS;

-- OWNER table
CREATE TABLE OWNER (
    OWNER_ID NUMBER PRIMARY KEY,
    OWNER_NAME VARCHAR2(100) NOT NULL,
    CONTACT_NUMBER VARCHAR2(20)
);

-- VEHICLE table
CREATE TABLE VEHICLE (
    VEHICLE_ID NUMBER PRIMARY KEY,
    OWNER_ID NUMBER REFERENCES OWNER(OWNER_ID),
    VEHICLE_NUMBER VARCHAR2(20) NOT NULL UNIQUE,
    VEHICLE_TYPE VARCHAR2(20)
);

-- RESERVATION_SLOT_DETAILS table (normalized)
CREATE TABLE RESERVATION_SLOT_DETAILS (
    RESERVATION_ID NUMBER PRIMARY KEY,
    SLOT_ID NUMBER NOT NULL,
    SLOT_START_TIME VARCHAR2(20) NOT NULL,
    SLOT_END_TIME VARCHAR2(20) NOT NULL,
    SLOT_BOOKING_STATUS VARCHAR2(20) NOT NULL,
    RESERVATION_STATUS VARCHAR2(20) NOT NULL,
    VEHICLE_ID NUMBER REFERENCES VEHICLE(VEHICLE_ID)
);